name: jobfinder
description: A job finder app done in flutter

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  pedantic:
  auto_size_text:
  shimmer:
  logger:
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  flutter_lints:

flutter:
  uses-material-design: true

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf

    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-Regular.ttf
